# ======================================================================================================================
# == LICENSE:       Copyright (c) 2023 Kevin De Coninck
# ==
# ==                Permission is hereby granted, free of charge, to any person
# ==                obtaining a copy of this software and associated documentation
# ==                files (the "Software"), to deal in the Software without
# ==                restriction, including without limitation the rights to use,
# ==                copy, modify, merge, publish, distribute, sublicense, and/or sell
# ==                copies of the Software, and to permit persons to whom the
# ==                Software is furnished to do so, subject to the following
# ==                conditions:
# ==
# ==                The above copyright notice and this permission notice shall be
# ==                included in all copies or substantial portions of the Software.
# ==
# ==                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# ==                EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# ==                OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# ==                NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# ==                HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# ==                WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# ==                FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# ==                OTHER DEALINGS IN THE SOFTWARE.
# ======================================================================================================================

# Defines how releases are managed on GitHub.
changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver major
    - title: Exciting New Features 🎉
      labels:
        - Semver minor
    - title: Bug fixes 🐞
      labels:
        - Bugfix
    - title: Breaking Changes (Identity & access management) 🛠
      labels:
        - IAM (Semver major)
    - title: Exciting New Features (Identity & access management) 🎉
      labels:
        - IAM (Semver minor)
    - title: Bug fixes (Identity & access management) 🐞
      labels:
        - IAM (Bugfix)
    - title: Breaking Changes (Identity & access management) 🛠
      labels:
        - User Management (Semver major)
    - title: Exciting New Features (User Management) 🎉
      labels:
        - User Management (Semver minor)
    - title: Bug fixes (User Management) 🐞
      labels:
        - User Management (Bugfix)
